# permissions for end users to edit besugeneses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: besugenesis-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: bevel-operator-besu
    app.kubernetes.io/part-of: bevel-operator-besu
    app.kubernetes.io/managed-by: kustomize
  name: besugenesis-editor-role
rules:
- apiGroups:
  - charts.besu.bevel.io
  resources:
  - besugeneses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - charts.besu.bevel.io
  resources:
  - besugeneses/status
  verbs:
  - get
