dependencies:
  - name: bevel-vault-mgmt
    repository: "https://hyperledger.github.io/bevel"
    tags:
      - bevel
    version: ~1.0.0
  - name: bevel-scripts
    repository: "https://hyperledger.github.io/bevel"
    tags:
      - bevel
    version: ~1.0.0
