##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---
# The following are for overriding global values
global:
  #Provide the service account name which will be created.
  serviceAccountName: vault-auth
  cluster:
    provider: aws  # choose from: minikube | aws
    cloudNativeServices: false # 'false' is implemented
    #Provide the kubernetes host url
    #Eg. kubernetesUrl: https://10.3.8.5:6443
    kubernetesUrl: 
  vault:
    #Provide the type of vault
    type: hashicorp
    #Provide the vault role used.
    role: vault-role
    #Provide the network type
    network: besu
    #Provide the vault server address
    address: 
    #Provide the vault authPath configured to be used.
    authPath: supplychain
    #Provide the secret engine.
    secretEngine: secretsv2
    #Provide the vault path where the secrets will be stored
    secretPrefix: "data/supplychain"
  
image:
  #Provide the image for the job/hook container
  genesisUtils:
    repository: ghcr.io/hyperledger/bevel-k8s-hooks
    tag: qgt-0.2.12
  #Provide the secret to use if private repository
  #Eg. pullSecret: regcred
  pullSecret: 
  #Pull policy to be used for the Docker image
  pullPolicy: IfNotPresent

settings:
  # Flag to ensure the genesis configmap is removed on helm uninstall
  removeGenesisOnDelete: true
  # Flag to copy genesis and static nodes from files for secondary members
  secondaryGenesis: false

# the raw Genesis config
# rawGenesisConfig.blockchain.nodes set the number of validators/signers
rawGenesisConfig:
  genesis:
    config:
      chainId: 1337
      algorithm:
        consensus: qbft   # choose from: ibft2 | qbft | clique
        blockperiodseconds: 10
        epochlength: 30000
        requesttimeoutseconds: 20
    gasLimit: '0xf7b760' 
    difficulty: '0x1'
    coinbase: '0x0000000000000000000000000000000000000000'
    contractSizeLimit: 2147483647
    transactionSizeLimit: 128
    includeQuickStartAccounts: false
    additionalAccounts: []
    permissioning: false
  blockchain:
    nodes:
      generate: true
      count: 4
    accountPassword: 'password'
